import type { User } from '@shega/shared';
import { AuthProvider } from '@shega/ui';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { Inter } from 'next/font/google';
import MantineThemeProvider from 'providers/MantineProviders';
import QueryProviders from 'providers/Query.provider';
import { type ReactNode, Suspense } from 'react';
import { generateColors, lightenHexColor } from 'utility/colors';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Turborepo',
    description: 'Generated by create turbo',
};

type Props = {
    children: ReactNode;
    params: Promise<{ locale: string }>;
};

//greenish theme
const defaultTheme = '#22C55E';
export default async function RootLayout(props: Props) {
    const params = await props.params;
    const { locale } = params;
    const { children } = props;

    const messages = await getMessages();
    const colorArray = generateColors(defaultTheme);
    const styles: Record<string, string> = {
        '--primary-color-default': defaultTheme,
        '--primary-radius': '8px',
        backgroundColor: lightenHexColor(defaultTheme, 98) || '#f5fbfe',
    };

    colorArray.forEach((color, index) => {
        styles[`--primary-color-${index}`] = color;
    });
    const user: User = {
        accountId: '',
        userId: '',
        firstName: { en: 'test' },
        lastName: { en: 'test' },
        isPhoneVerified: false,
        isEmailVerified: false,
        preferredLanguage: '',
        permissions: [],
    };

    return (
        <html lang={locale}>
            <body suppressHydrationWarning={true}>
                <QueryProviders>
                    <NextIntlClientProvider messages={messages}>
                        <MantineThemeProvider
                            color={defaultTheme}
                            radius={'8px'}
                        >
                            <AuthProvider user={user}>
                                <Suspense>{children}</Suspense>
                            </AuthProvider>
                        </MantineThemeProvider>
                    </NextIntlClientProvider>
                </QueryProviders>
            </body>
        </html>
    );
}
