import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import MantineThemeProvider from 'providers/MantineProviders';
import { PropsWithChildren } from 'react';
import { generateColors, lightenHexColor } from 'utility/colors';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Turborepo',
    description: 'Generated by create turbo',
};

//greenish theme
const defaultTheme = 'red';

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
    const colorArray = generateColors(defaultTheme);
    const styles: Record<string, string> = {
        '--primary-color-default': defaultTheme,
        '--primary-radius': '8px',
        backgroundColor: lightenHexColor(defaultTheme, 98) || '#f5fbfe',
    };

    colorArray.forEach((color, index) => {
        styles[`--primary-color-${index}`] = color;
    });
    return (
        <html lang="en">
            <body className={inter.className}>
                <MantineThemeProvider color={defaultTheme} radius={'8px'}>
                    {children}
                </MantineThemeProvider>
            </body>
        </html>
    );
}
