variables:
  GIT_DEPTH: "0" # Tells git to fetch all the branches of the project, required by the analysis taskk

default:
  image: node:22

stages:
  - build
  - staging

build:
  stage: build
  image: node:22
  only:
    - merge_requests
  before_script:
    - npm install --global corepack@latest
    - corepack enable
    - corepack prepare pnpm@9.0.0 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - pnpm run format:error
    - pnpm run build

staging:
  stage: staging
  image: node:22
  only:
    - develop
  before_script:
    - npm install --global corepack@latest
    - corepack enable
    - corepack prepare pnpm@latest-10 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - pnpm run format
    - pnpm run build
    - |
      curl -X GET "$COOLIFY_URL/api/v1/deploy?tag=shega&force=false" -H "Authorization: Bearer $COOLIFY_DEPLOY_TOKEN"

  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
