import { AuthProvider } from '@shega/ui';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { Inter } from 'next/font/google';
import MantineThemeProvider from 'providers/MantineProviders';
import QueryProviders from 'providers/Query.provider';
import type { PropsWithChildren } from 'react';
import { generateColors, lightenHexColor } from 'utility/colors';
import { getUserAction } from './_api/get-user-action';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Turborepo',
    description: 'Generated by create turbo',
};

//bluish theme
const defaultTheme = '#014d4e';

export default async function RootLayout({
    children,
}: Readonly<PropsWithChildren>) {

    const user = await getUserAction();

    const messages = await getMessages();

    const colorArray = generateColors(defaultTheme);
    const styles: Record<string, string> = {
        '--primary-color-default': defaultTheme,
        '--primary-radius': '8px',
        backgroundColor: lightenHexColor(defaultTheme, 98) || '#014d4e',
    };

    colorArray.forEach((color, index) => {
        styles[`--primary-color-${index}`] = color;
    });
    return (
        <html lang="en">
            <body className={inter.className}>
                <NextIntlClientProvider messages={messages}>
                    <QueryProviders>
                        <MantineThemeProvider
                            color={defaultTheme}
                            radius={'8px'}
                        >
                            <AuthProvider user={user}>
                                {children}
                            </AuthProvider>
                        </MantineThemeProvider>
                    </QueryProviders>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
